---
on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * *"

jobs:
  main:
    runs-on: self-hosted
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Retrieve Harts Mead info
        run: |
          curl https://www.taylorwimpey.co.uk/new-homes/ashton-under-lyne/harts-mead \
          | awk -f hartsmead.awk \
          | tee hartsmead.html

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Harts Mead Available Plots
          to: qmacro@gmail.com
          from: qmacro automation <qmacrodev@gmail.com>
          html_body: file://hartsmead.html
