---
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: self-hosted
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Retrieve Harts Mead info
        run: echo "INFO=$(curl https://www.taylorwimpey.co.uk/new-homes/ashton-under-lyne/harts-mead | awk -f hartsmead.awk)" >> $GITHUB_ENV

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          to: qmacro@gmail.com
          # Required sender full name (address can be skipped):
          from: qmacro automation <qmacrodev@gmail.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: ${{ env.INFO }}
