---
on:
  issues:
    types: [labeled]

jobs:
  main:
    runs-on: ubuntu-22.04
    env:
      LABEL: "contribution"
    if: contains(github.repositoryUrl, 'github.com') && github.event.label.name == $LABEL
    steps:

      - name: Show the label value
        run: echo "Label is $LABEL"

      - name: Emit event context
        run: echo "${{ toJSON(github.event) }}"
