---
name: label-contribution
on:
  issues:
    types: [labeled]


jobs:
  main:

    runs-on: ubuntu-22.04

    env:
      LABEL: "contribution"

    if: contains(github.repositoryUrl, 'github.com') && github.event.label.name == 'contribution'

    steps:

      - name: GITHUB_EVENT
        env:
          GITHUB_EVENT: ${{ tojson(github.event) }}
        run: true

      - name: Show the label value
        run: echo "Label is $LABEL"
