---
name: label-contribution
on:
  issues:
    types: [labeled]


jobs:
  main:

    runs-on: ubuntu-22.04

    env:
      LABEL: "contribution"
      GITHUB_CONTEXT: ${{ tojson(github.event) }}

    if: contains(github.repositoryUrl, 'github.com') && github.event.label.name == 'contribution'

    steps:

      - name: Show the label value
        run: echo "Label is $LABEL"

      - name: Emit event context
        run: echo "$GITHUB_CONTEXT"
