---
name: label-any
on:
  issues:
    types: [labeled]

jobs:
  main:
    runs-on: ubuntu-22.04

    if: contains(github.repositoryUrl, 'github.com')

    env:
      GITHUB_CONTEXT: ${{ toJSON(github.event) }}

    steps:

      - name: Emit event context
        run: echo "${{ toJSON(github.event) }}"
