---
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: self-hosted
    steps:

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME_REPO}}
          password: ${{secrets.MAIL_PASSWORD_REPO}}
          # Required mail subject:
          subject: Github Actions job result
          to: qmacro@gmail.com
          # Required sender full name (address can be skipped):
          from: qmacro automation <qmacrodev@gmail.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
